//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Comments = new HashSet<Comments>();
            this.SoldProducts = new HashSet<SoldProducts>();
            this.ProductImages = new HashSet<ProductImages>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ExtraDescription { get; set; }
        public string Photo { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> NumberOfSales { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string seoUrl { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Categories Categories1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoldProducts> SoldProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
    }
}
